### ISSUE TITLE
String commands

### ISSUE THREAD

**Issue by gillchristian** [ndelvalle/rustdis#30]
All [string commands](https://redis.io/docs/latest/commands/?group=string) (without options)

- [x] APPEND
- [x] DECR #32
- [x] DECRBY #32
- [x] GET
- [x] GETDEL
- [x] GETRANGE
- [x] INCR #32
- [x] INCRBY #32
- [x] INCRBYFLOAT #35 
- [x] LCS #31
- [x] MGET #34 
- [x] MSET #34 
- [x] MSETNX #34 
- [x] SET
- [x] SETNX
- [x] SETRANGE #33
- [x] STRLEN
- [ ] GETEX ~ requires TTL
- [ ] ~SETEX~ deprecated
- [ ] ~GETSET~ deprecated
- [ ] ~SUBSTR~ deprecated
- [ ] ~PSETEX~ deprecated

**Comment by ndelvalle** [comment]
@gillchristian [GETSET](https://redis.io/docs/latest/commands/getset/) is deprecated, should we skip that one?
